"""
Django settings for capstone_backend project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import json
from dotenv import load_dotenv
from cryptography.fernet import Fernet
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key
from config.mongodb import LazyMongoDatabase

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = get_random_secret_key()
    else:
        raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG=False")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'axes',
    'channels',
    'accounts',
    'profiles',
    'documents',
    'ai_assistant',
    'loans',
    'notifications',
    'analytics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  
    'config.middleware.SecurityHeadersMiddleware',
    'django.middleware.common.CommonMiddleware',
    'config.middleware.NoSQLInjectionGuardMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'config.middleware.CSRFSameSiteTokenMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ASGI Application
ASGI_APPLICATION = "config.asgi.application"

# WebSocket settings
WEBSOCKET_ENABLED = env_bool("WEBSOCKET_ENABLED", True)

# Channel Layers Configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.environ.get('REDIS_HOST', 'localhost'), 6379)],
        },
    },
}

# Database - MongoDB only (via PyMongo)
# Dummy database config required by Django
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    }
}

# MongoDB Configuration
MONGODB_URI = os.getenv('MONGODB_URI', '')
MONGODB_NAME = os.getenv('MONGODB_NAME', 'capstone_db')
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY', '').strip()

# Production must never store sensitive fields as plaintext.
# In DEBUG/development, allow plaintext pass-through so local setups do not require key management.
if not DEBUG:
    if not FIELD_ENCRYPTION_KEY:
        raise ImproperlyConfigured("FIELD_ENCRYPTION_KEY must be set when DEBUG=False")
    try:
        Fernet(FIELD_ENCRYPTION_KEY.encode('utf-8'))
    except Exception as exc:
        raise ImproperlyConfigured(
            'FIELD_ENCRYPTION_KEY is invalid. Generate one with: '
            'python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"'
        ) from exc

# Configure a lazy PyMongo handle. This deliberately performs no DNS lookup or
# socket work while Django settings, management commands, or tests are importing.
if MONGODB_URI:
    MONGODB = LazyMongoDatabase(MONGODB_URI, MONGODB_NAME)
    MONGO_CLIENT = None  # client is available lazily as MONGODB.client
else:
    MONGO_CLIENT = None
    MONGODB = None


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# django-axes settings
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # 1 hour
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username"]
AXES_HANDLER = 'axes.handlers.cache.AxesCacheHandler'
# MongoDB account lockouts are authoritative. Axes records and resets attempts
# but does not impose a second, conflicting lockout duration.
AXES_LOCK_OUT_AT_FAILURE = False


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For collectstatic in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Document Storage Configuration
# Options: 'local', 's3', 'gcs' (cloud backends to be implemented)
DOCUMENT_STORAGE_BACKEND = 'local'
DOCUMENT_UPLOAD_AI_ANALYSIS = os.getenv('DOCUMENT_UPLOAD_AI_ANALYSIS', 'True') == 'True'
DOCUMENT_UPLOAD_NOTIFY_REVIEWERS = os.getenv('DOCUMENT_UPLOAD_NOTIFY_REVIEWERS', 'True') == 'True'
DOCUMENT_UPLOAD_NOTIFY_ASYNC = os.getenv('DOCUMENT_UPLOAD_NOTIFY_ASYNC', 'True') == 'True'

# Cache Configuration
# Development may use process-local memory. Production requires Redis so DRF
# throttles and django-axes observe one shared counter across all workers.
_configured_redis_url = os.getenv('REDIS_URL')
REDIS_URL = _configured_redis_url or os.getenv(
    'CELERY_BROKER_URL', 'redis://localhost:6379/0'
)
USE_REDIS_CACHE = env_bool('USE_REDIS_CACHE', not DEBUG)

if not DEBUG and not USE_REDIS_CACHE:
    raise ImproperlyConfigured(
        "USE_REDIS_CACHE must be enabled when DEBUG=False so authentication "
        "throttles and django-axes use shared state"
    )
if not DEBUG and not _configured_redis_url:
    raise ImproperlyConfigured(
        "REDIS_URL must be explicitly configured when DEBUG=False so the "
        "Django cache uses a Redis-compatible connection"
    )

if USE_REDIS_CACHE and REDIS_URL:
    # Use Django's built-in Redis cache (Django 4.0+)
    # Compatible with redis>=4.0
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'KEY_PREFIX': 'msme_ai',
        }
    }
else:
    # Local memory cache (good for single-server deployments)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'msme-ai-cache',
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        }
    }

# Cache TTL settings (in seconds)
CACHE_TTL = {
    'faqs': 60 * 60 * 24,       # 24 hours - FAQs rarely change
    'education': 60 * 60 * 24,   # 24 hours - education content rarely changes
    'suggestions': 60 * 60 * 12, # 12 hours - suggestions are static
    'loan_products': 60 * 30,    # 30 minutes - products may be updated by admin
    'ai_status': 60,             # 1 minute - status should be fresh
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configuration
try:
    TRUSTED_PROXY_COUNT = int(os.getenv('TRUSTED_PROXY_COUNT', '0'))
except ValueError as exc:
    raise ImproperlyConfigured("TRUSTED_PROXY_COUNT must be an integer") from exc
if TRUSTED_PROXY_COUNT < 0:
    raise ImproperlyConfigured("TRUSTED_PROXY_COUNT cannot be negative")

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.CustomJWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # Do not trust client-supplied forwarding headers by default. Set this to the
    # exact number of trusted reverse proxies when deploying behind a proxy chain.
    'NUM_PROXIES': TRUSTED_PROXY_COUNT,
}

# JWT Settings
from datetime import timedelta

# Single source of truth for token lifetimes across all roles.
TOKEN_LIFETIMES = {
    'remember_me': {
        'access': timedelta(minutes=30),
        'refresh': timedelta(days=30),
    },
    'no_remember_me': {
        'access': timedelta(minutes=30),
        'refresh': timedelta(days=7),
    },
    'signup': {
        'access': timedelta(minutes=30),
        'refresh': timedelta(days=7),
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': TOKEN_LIFETIMES['no_remember_me']['access'],
    'REFRESH_TOKEN_LIFETIME': TOKEN_LIFETIMES['no_remember_me']['refresh'],
    'ROTATE_REFRESH_TOKENS': False,  # Disabled since we're using MongoDB
    'BLACKLIST_AFTER_ROTATION': False,  # Disabled - using custom MongoDB blacklist
    'AUTH_HEADER_TYPES': ('Bearer',),
    'CHECK_REVOKE_TOKEN': False,  # Disable built-in token revocation check
}

# CORS configuration
if env_bool('CORS_ALLOW_ALL_ORIGINS', False):
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://localhost:5173').split(',')
CORS_ALLOW_CREDENTIALS = True

# CSRF / SameSite policy
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_HTTPONLY = env_bool('SESSION_COOKIE_HTTPONLY', True)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_HTTPONLY = env_bool('CSRF_COOKIE_HTTPONLY', False)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', not DEBUG)
AUTH_ACCESS_COOKIE_NAME = os.getenv('AUTH_ACCESS_COOKIE_NAME', 'access_token')
AUTH_REFRESH_COOKIE_NAME = os.getenv('AUTH_REFRESH_COOKIE_NAME', 'refresh_token')
AUTH_COOKIE_SECURE = env_bool('AUTH_COOKIE_SECURE', not DEBUG)
AUTH_COOKIE_HTTPONLY = env_bool('AUTH_COOKIE_HTTPONLY', True)
AUTH_COOKIE_SAMESITE = os.getenv('AUTH_COOKIE_SAMESITE', 'Lax')
AUTH_COOKIE_PATH = os.getenv('AUTH_COOKIE_PATH', '/')
AUTH_ACCESS_COOKIE_PATH = os.getenv('AUTH_ACCESS_COOKIE_PATH', '/api/')
AUTH_REFRESH_COOKIE_PATH = os.getenv('AUTH_REFRESH_COOKIE_PATH', '/api/auth/')
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173'
    ).split(',')
    if origin.strip()
]

# Email configuration
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
_email_backend = os.getenv('EMAIL_BACKEND')
_placeholder_email_values = {
    '',
    'your-email@gmail.com',
    'your-16-character-app-password',
    'your-app-password',
}
_email_values_look_placeholder = (
    EMAIL_HOST_USER.strip().lower() in _placeholder_email_values
    or EMAIL_HOST_PASSWORD.strip().lower() in _placeholder_email_values
    or EMAIL_HOST_USER.strip().startswith('your-')
    or EMAIL_HOST_PASSWORD.strip().startswith('your-')
)
if _email_backend:
    if DEBUG and _email_backend == 'django.core.mail.backends.smtp.EmailBackend' and _email_values_look_placeholder:
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    else:
        EMAIL_BACKEND = _email_backend
elif DEBUG and _email_values_look_placeholder:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', 10))
# Recipient address for the public contact/support form.
SUPPORT_EMAIL = os.getenv('SUPPORT_EMAIL', 'sorianoeligabriel@gmail.com')

# Templates configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Celery Configuration
ACCOUNT_DELETION_RETENTION_DAYS = int(
    os.getenv("ACCOUNT_DELETION_RETENTION_DAYS", "30")
)
TWO_FACTOR_RECOVERY_APPROVAL_HOURS = int(
    os.getenv("TWO_FACTOR_RECOVERY_APPROVAL_HOURS", "24")
)

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_ROUTES = {
    'blockchain.*': {'queue': 'blockchain'},
    'loans.execute_wallet_disbursement_task': {'queue': 'blockchain'},
}

# MongoDB-backed leases coordinate the single configured blockchain sender.
BLOCKCHAIN_NONCE_LOCK_WAIT_SECONDS = 15
BLOCKCHAIN_NONCE_LEASE_SECONDS = 180
BLOCKCHAIN_RECONCILIATION_BATCH_SIZE = 250

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'authentication.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'authentication': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'admin_auth': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'loan_officer_auth': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'blockchain': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# =============================================================================
# PRODUCTION SECURITY SETTINGS
# =============================================================================
# These settings are only active when DEBUG=False (production)

if not DEBUG:
    # Force HTTPS
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', True)
    
    # Secure cookies
    SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', True)
    CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', True)
    
    # Use console logging only in production (Railway captures stdout)
    LOGGING['handlers'] = {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    }
    for logger_name in ('authentication', 'admin_auth', 'loan_officer_auth'):
        LOGGING['loggers'][logger_name]['handlers'] = ['console']

# Groq LLM Configuration
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')
GROQ_MODEL = os.getenv('GROQ_MODEL', 'llama-3.1-8b-instant')
GROQ_CHAT_MODEL = os.getenv('GROQ_CHAT_MODEL', GROQ_MODEL)

# Consent policy deployed by this backend. Clients must present this version
# when granting consent; changing it automatically requires re-consent.
CONSENT_POLICY_ID = os.getenv('CONSENT_POLICY_ID', 'privacy-and-ai-consent')
CONSENT_POLICY_VERSION = os.getenv('CONSENT_POLICY_VERSION', '2026-08-01')
CONSENT_POLICY_EFFECTIVE_AT = os.getenv(
    'CONSENT_POLICY_EFFECTIVE_AT', '2026-08-01T00:00:00Z'
)
CONSENT_POLICY_DOCUMENT_URI = os.getenv(
    'CONSENT_POLICY_DOCUMENT_URI', 'docs/feats/PRIVACY_POLICY.md'
)
CONSENT_POLICY_CONTENT_SHA256 = os.getenv(
    'CONSENT_POLICY_CONTENT_SHA256',
    'f996fc9a8ad51a1d7f33b95072333614ddef845dc66daa50088efd4cb6b2aa02',
)
GROQ_QUALIFICATION_MODEL = os.getenv('GROQ_QUALIFICATION_MODEL', GROQ_MODEL)

# LLM Provider Configuration
# Set LLM_PROVIDER to 'groq' or 'ollama' to switch AI backends
LLM_PROVIDER = os.getenv('LLM_PROVIDER', 'groq')
OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', 'http://localhost:11434')
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'llama3.1')

# =============================================================================
# BLOCKCHAIN INTEGRATION (Smart Contracts via web3.py)
# =============================================================================

# Kill switch — set to True to enable blockchain sync
BLOCKCHAIN_ENABLED = env_bool('BLOCKCHAIN_ENABLED', False)

# RPC endpoint (Ganache local, or testnet/mainnet URL)
BLOCKCHAIN_RPC_URL = os.getenv('BLOCKCHAIN_RPC_URL', 'http://127.0.0.1:7545')

# Chain ID (1337=Ganache, 31337=Hardhat, 11155111=Sepolia, 137=Polygon)
BLOCKCHAIN_CHAIN_ID = int(os.getenv('BLOCKCHAIN_CHAIN_ID', '1337'))

# Backend service wallet private key (signs all on-chain transactions)
BLOCKCHAIN_WALLET_KEY = os.getenv('BLOCKCHAIN_WALLET_KEY', '')

# Deployed contract addresses (JSON string from env, or loaded from deployment file)
_contract_addresses_raw = os.getenv('BLOCKCHAIN_CONTRACT_ADDRESSES', '')
if _contract_addresses_raw:
    BLOCKCHAIN_CONTRACT_ADDRESSES = json.loads(_contract_addresses_raw)
else:
    BLOCKCHAIN_CONTRACT_ADDRESSES = {}

# Gas settings
BLOCKCHAIN_GAS_LIMIT = int(os.getenv('BLOCKCHAIN_GAS_LIMIT', '6721975'))
BLOCKCHAIN_GAS_PRICE_GWEI = int(float(os.getenv('BLOCKCHAIN_GAS_PRICE_GWEI', '20')))

# Block explorer URL (e.g. https://etherscan.io, https://sepolia.etherscan.io)
# Leave empty for local Ganache (no explorer available)
BLOCKCHAIN_EXPLORER_URL = os.getenv('BLOCKCHAIN_EXPLORER_URL', '')

# Confirmations required before an incoming ETH transfer can be posted as a loan
# payment. Production networks should tune this based on their reorg risk.
LOANS_WALLET_MIN_CONFIRMATIONS = int(
    os.getenv('LOANS_WALLET_MIN_CONFIRMATIONS', '3')
)

# Path to ABI files (relative to BASE_DIR)
BLOCKCHAIN_ABI_DIR = BASE_DIR / 'loans' / 'blockchain' / 'abis'
